import {
  SiReact, SiNextdotjs, SiTypescript, SiJavascript, SiHtml5, SiCss,
  SiTailwindcss, SiSass, SiNodedotjs, SiExpress, SiPhp, SiMysql,
  SiPostgresql, SiMongodb, SiCplusplus, SiPython, SiGit, SiGithub,
  SiDocker, SiLinux, SiFigma, SiVscodium, SiPostman, SiC,
  SiFirebase, SiSupabase, SiPrisma, SiGraphql, SiRedux,
  SiVuedotjs, SiNuxt, SiSvelte, SiAngular,
  SiLaravel, SiDjango, SiFlask, SiFastapi, SiSpring,
  SiRedis, SiSqlite, SiMariadb,
  SiGooglecloud, SiVercel, SiNetlify, SiNginx,
  SiKubernetes, SiJest, SiCypress, SiWebpack, SiVite,
  SiStripe, SiTwilio, SiOpenai,
  SiJira, SiNotion, SiSlack,
  SiRust, SiGo, SiKotlin, SiSwift, SiDart, SiFlutter,
  SiStyledcomponents, SiBootstrap, SiMui,
  SiSocketdotio, SiNestjs, SiFastify,
  SiZapier, SiGnubash, SiGoogle, SiMeta,
  SiCanva,
} from "react-icons/si";
import type { IconType } from "react-icons";

// ─── Canonical icon registry (Si icon name → component) ──────────────────────
// Add entries here to support new icons across the entire portfolio.

export const iconRegistry: Record<string, IconType> = {
  SiReact, SiNextdotjs, SiTypescript, SiJavascript, SiHtml5, SiCss,
  SiTailwindcss, SiSass, SiNodedotjs, SiExpress, SiPhp, SiMysql,
  SiPostgresql, SiMongodb, SiCplusplus, SiPython, SiGit, SiGithub,
  SiDocker, SiLinux, SiFigma, SiVscodium, SiPostman, SiC,
  SiFirebase, SiSupabase, SiPrisma, SiGraphql, SiRedux,
  SiVuedotjs, SiNuxt, SiSvelte, SiAngular,
  SiLaravel, SiDjango, SiFlask, SiFastapi, SiSpring,
  SiRedis, SiSqlite, SiMariadb,
  SiGooglecloud, SiVercel, SiNetlify, SiNginx,
  SiKubernetes, SiJest, SiCypress, SiWebpack, SiVite,
  SiStripe, SiTwilio, SiOpenai,
  SiJira, SiNotion, SiSlack,
  SiRust, SiGo, SiKotlin, SiSwift, SiDart, SiFlutter,
  SiStyledcomponents, SiBootstrap, SiMui,
  SiSocketdotio, SiNestjs, SiFastify,
  SiZapier, SiGnubash, SiGoogle, SiMeta,
  SiCanva,
};

// ─── Normalized name → icon lookup (for Projects & Experience tech tags) ──────
// Keys are lowercased for case-insensitive matching.

const nameToIcon: Record<string, IconType> = {
  react: SiReact,
  "react.js": SiReact,
  reactjs: SiReact,
  "next.js": SiNextdotjs,
  nextjs: SiNextdotjs,
  next: SiNextdotjs,
  typescript: SiTypescript,
  ts: SiTypescript,
  javascript: SiJavascript,
  js: SiJavascript,
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss,
  css3: SiCss,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  sass: SiSass,
  scss: SiSass,
  "node.js": SiNodedotjs,
  nodejs: SiNodedotjs,
  node: SiNodedotjs,
  express: SiExpress,
  "express.js": SiExpress,
  expressjs: SiExpress,
  php: SiPhp,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  mongodb: SiMongodb,
  mongo: SiMongodb,
  "c++": SiCplusplus,
  cpp: SiCplusplus,
  python: SiPython,
  git: SiGit,
  github: SiGithub,
  docker: SiDocker,
  linux: SiLinux,
  ubuntu: SiLinux,
  figma: SiFigma,
  vscode: SiVscodium,
  "vs code": SiVscodium,
  postman: SiPostman,
  c: SiC,
  firebase: SiFirebase,
  supabase: SiSupabase,
  prisma: SiPrisma,
  graphql: SiGraphql,
  redux: SiRedux,
  "vue.js": SiVuedotjs,
  vuejs: SiVuedotjs,
  vue: SiVuedotjs,
  "nuxt.js": SiNuxt,
  nuxtjs: SiNuxt,
  nuxt: SiNuxt,
  svelte: SiSvelte,
  angular: SiAngular,
  laravel: SiLaravel,
  django: SiDjango,
  flask: SiFlask,
  fastapi: SiFastapi,
  spring: SiSpring,
  redis: SiRedis,
  sqlite: SiSqlite,
  mariadb: SiMariadb,
  gcp: SiGooglecloud,
  "google cloud": SiGooglecloud,
  googlecloud: SiGooglecloud,
  vercel: SiVercel,
  netlify: SiNetlify,
  nginx: SiNginx,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  jest: SiJest,
  cypress: SiCypress,
  webpack: SiWebpack,
  vite: SiVite,
  stripe: SiStripe,
  twilio: SiTwilio,
  openai: SiOpenai,
  jira: SiJira,
  notion: SiNotion,
  slack: SiSlack,
  rust: SiRust,
  go: SiGo,
  golang: SiGo,
  kotlin: SiKotlin,
  swift: SiSwift,
  dart: SiDart,
  flutter: SiFlutter,
  "styled-components": SiStyledcomponents,
  "styled components": SiStyledcomponents,
  bootstrap: SiBootstrap,
  mui: SiMui,
  "material ui": SiMui,
  "socket.io": SiSocketdotio,
  socketio: SiSocketdotio,
  nestjs: SiNestjs,
  "nest.js": SiNestjs,
  fastify: SiFastify,
  zapier: SiZapier,
  bash: SiGnubash,
  gnubash: SiGnubash,
  "bash scripting": SiGnubash,
  google: SiGoogle,
  "seo technique": SiGoogle,
  "sea google/meta": SiMeta,
  meta: SiMeta,
  facebook: SiMeta,
};

/**
 * Look up a react-icons/si icon by tech display name (case-insensitive).
 * Returns null if no icon is found.
 */
export function getTechIcon(name: string): IconType | null {
  return nameToIcon[name.toLowerCase().trim()] ?? null;
}

/**
 * Look up an icon by its Si key name (e.g. "SiReact").
 * Used for skill items stored in Firestore.
 */
export function getIconByKey(key: string): IconType | null {
  return iconRegistry[key] ?? null;
}
